import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKotlinMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

kotlin {
    android {
        namespace = "s4y.yopt.compose"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }
    jvm("desktop") {
        mainRun {
            mainClass.set("s4y.yopt.MainKt")
        }
    }

    val xcf = XCFramework("ComposeApp")
    listOf(iosArm64(), iosSimulatorArm64()).forEach {
        it.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            xcf.add(this)
        }
    }
    macosArm64() {
        binaries {
            framework {
                baseName = "ComposeApp"
                isStatic = true
                xcf.add(this)
            }
            executable {
                entryPoint = "s4y.yopt.main"
            }
        }
    }

    wasmJs {
        browser()
        binaries.executable()
    }
    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(projects.shared)
            implementation(libs.markdown.renderer)
            implementation(libs.markdown.renderer.m3)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation("org.slf4j:slf4j-simple:1.7.36")
            }
        }
        wasmJsMain.dependencies {
            implementation(libs.kotlinx.browser)
        }
    }
}

compose.desktop {
    application {
        mainClass = "s4y.yopt.MainKt"
    }
}

// Generated by prepareComposeResourcesTaskForCommonMain.
// This directory IS the "composeResources/" layer; it contains values/, drawable/, etc. directly.
// The module qualifier must be added as a destination subdir when copying into bundles.
val preparedResourcesSrcDir = layout.buildDirectory.dir(
    "generated/compose/resourceGenerator/preparedResources/commonMain/composeResources"
)
// Module qualifier used by DefaultMacOsResourceReader:
//   NSBundle.mainBundle.resourcePath + "/compose-resources/composeResources/<qualifier>/values/strings.cvr"
val composeResourcesModulePath = "yopt.composeapp.generated.resources"

tasks.register("packageMacosApp") {
    dependsOn("linkReleaseExecutableMacosArm64", "prepareComposeResourcesTaskForCommonMain")

    val appName = "YoPt"
    val contentsDir = layout.buildDirectory.dir("macos/$appName.app/Contents")
    val binaryFile = layout.buildDirectory.file("bin/macosArm64/releaseExecutable/composeApp.kexe")
    val svgIcon = layout.projectDirectory.file("../assets/icon.svg")
    val srcDir = preparedResourcesSrcDir
    val modulePath = composeResourcesModulePath
    inputs.file(binaryFile)
    inputs.file(svgIcon)
    inputs.dir(srcDir)
    outputs.dir(contentsDir)

    // Resolve to File at configuration time — doLast captures only serializable java.io.File refs,
    // avoiding "cannot serialize Gradle script object references" config-cache errors.
    val contentsDirFile = contentsDir.get().asFile
    val binaryFileFile = binaryFile.get().asFile
    val svgIconFile = svgIcon.asFile
    val srcDirFile = srcDir.get().asFile

    doLast {
        val macosDir = contentsDirFile.resolve("MacOS").also { it.mkdirs() }
        val resourcesDir = contentsDirFile.resolve("Resources").also { it.mkdirs() }

        // Copy + chmod binary
        val destBinary = macosDir.resolve(appName)
        binaryFileFile.copyTo(destBinary, overwrite = true)
        destBinary.setExecutable(true)

        // Copy compose resources into bundle at the path DefaultMacOsResourceReader expects:
        //   resourcePath/compose-resources/composeResources/<module>/values/strings.cvr
        if (srcDirFile.exists()) {
            val dst = resourcesDir
                .resolve("compose-resources")
                .resolve("composeResources")
                .resolve(modulePath)
            dst.deleteRecursively()
            srcDirFile.copyRecursively(dst, overwrite = true)
        }

        // SVG → iconset PNGs → .icns
        val iconsetDir = resourcesDir.resolve("$appName.iconset").also { it.mkdirs() }
        listOf(16, 32, 64, 128, 256, 512, 1024).forEach { size ->
            val out = iconsetDir.resolve("icon_${size}x${size}.png").absolutePath
            val exit = ProcessBuilder("rsvg-convert", "-w", "$size", "-h", "$size", svgIconFile.absolutePath, "-o", out)
                .inheritIO().start().waitFor()
            if (exit != 0) error("rsvg-convert failed at ${size}px (exit $exit)")
        }
        // iconset naming: @2x variants point to the next size up
        listOf(16 to 32, 32 to 64, 128 to 256, 256 to 512, 512 to 1024).forEach { (base, retina) ->
            iconsetDir.resolve("icon_${retina}x${retina}.png")
                .copyTo(iconsetDir.resolve("icon_${base}x${base}@2x.png"), overwrite = true)
        }
        val exit = ProcessBuilder(
            "iconutil", "--convert", "icns",
            "--output", resourcesDir.resolve("AppIcon.icns").absolutePath,
            iconsetDir.absolutePath,
        ).inheritIO().start().waitFor()
        if (exit != 0) error("iconutil failed (exit $exit)")
        iconsetDir.deleteRecursively()

        // Info.plist
        contentsDirFile.resolve("Info.plist").writeText("""
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>CFBundleDevelopmentRegion</key>
                <string>en</string>
                <key>CFBundleExecutable</key>
                <string>$appName</string>
                <key>CFBundleIconFile</key>
                <string>AppIcon</string>
                <key>CFBundleIdentifier</key>
                <string>s4y.yopt.mac</string>
                <key>CFBundleInfoDictionaryVersion</key>
                <string>6.0</string>
                <key>CFBundleName</key>
                <string>$appName</string>
                <key>CFBundlePackageType</key>
                <string>APPL</string>
                <key>CFBundleShortVersionString</key>
                <string>1.0</string>
                <key>CFBundleVersion</key>
                <string>1</string>
                <key>LSMinimumSystemVersion</key>
                <string>13.0</string>
                <key>NSHighResolutionCapable</key>
                <true/>
                <key>NSPrincipalClass</key>
                <string>NSApplication</string>
            </dict>
            </plist>
        """.trimIndent())

        println("✓ ${contentsDirFile.parent}")
    }
}

// Minimal .app bundle for runMacosNative.
// DefaultMacOsResourceReader (Compose 1.11.0) for a bundle binary resolves:
//   NSBundle.mainBundle.resourcePath + "/compose-resources/" + path
// = Contents/Resources/compose-resources/composeResources/<module>/values/strings.cvr
tasks.register("createDebugAppBundle") {
    dependsOn("linkDebugExecutableMacosArm64", "prepareComposeResourcesTaskForCommonMain")
    val appDir = layout.buildDirectory.dir("bin/macosArm64/debugExecutable/YoPt.app")
    val exeFile = layout.buildDirectory.file("bin/macosArm64/debugExecutable/composeApp.kexe")
    val srcDir = preparedResourcesSrcDir
    val modulePath = composeResourcesModulePath

    inputs.file(exeFile)
    inputs.dir(srcDir)
    outputs.dir(appDir)

    // Resolve to File at configuration time — doLast captures only serializable java.io.File refs.
    val appDirFile = appDir.get().asFile
    val exeFileFile = exeFile.get().asFile
    val macosDirFile = appDirFile.resolve("Contents/MacOS")
    val resourcesDirFile = appDirFile.resolve("Contents/Resources")
    val srcDirFile = srcDir.get().asFile

    doLast {
        val contents = appDirFile.resolve("Contents")
        macosDirFile.mkdirs()
        resourcesDirFile.mkdirs()

        // Copy + chmod binary
        val exeDst = macosDirFile.resolve("YoPt")
        exeFileFile.copyTo(exeDst, overwrite = true)
        exeDst.setExecutable(true)

        // Copy resources to compose-resources/composeResources/<module>/ inside the bundle.
        if (srcDirFile.exists()) {
            val dst = resourcesDirFile
                .resolve("compose-resources")
                .resolve("composeResources")
                .resolve(modulePath)
            dst.deleteRecursively()
            srcDirFile.copyRecursively(dst, overwrite = true)
        }

        // Minimal Info.plist so NSBundle recognizes the bundle
        contents.resolve("Info.plist").writeText("""<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0"><dict>
                <key>CFBundleExecutable</key><string>YoPt</string>
                <key>CFBundleIdentifier</key><string>s4y.yopt.mac</string>
                <key>CFBundleName</key><string>YoPt</string>
                <key>CFBundlePackageType</key><string>APPL</string>
            </dict></plist>""".trimIndent())
    }
}

// For a bare .kexe (non-bundle), NSBundle.mainBundle.resourcePath resolves to the directory
// containing the executable. DefaultMacOsResourceReader then looks for:
//   <executableDir>/compose-resources/composeResources/<module>/values/strings.cvr
// (same reader path as bundles: resourcePath + "/compose-resources/" + path)
// The KMP native resource pipeline never produces that tree (macosArm64 prepare tasks are
// NO-SOURCE because all resources live in commonMain). This task copies them there so
// runDebugExecutableMacosArm64 works without a bundle.
tasks.register("copyResourcesToMacosDebugExecutable") {
    dependsOn("prepareComposeResourcesTaskForCommonMain")
    val srcDir = preparedResourcesSrcDir
    // Reader: NSBundle.mainBundle.resourcePath + "/compose-resources/" + path
    // For a bare kexe, resourcePath == executableDir, so resources must land at:
    //   <executableDir>/compose-resources/composeResources/<module>/...
    val dstDir = layout.buildDirectory
        .dir("bin/macosArm64/debugExecutable/compose-resources/composeResources/$composeResourcesModulePath")
    inputs.dir(srcDir)
    outputs.dir(dstDir)
    val srcDirFile = srcDir.get().asFile
    val dstDirFile = dstDir.get().asFile
    doLast {
        dstDirFile.deleteRecursively()
        srcDirFile.copyRecursively(dstDirFile, overwrite = true)
    }
}

tasks.named("runDebugExecutableMacosArm64") {
    dependsOn("linkDebugExecutableMacosArm64", "copyResourcesToMacosDebugExecutable")
}

tasks.register("runMacosNative") {
    dependsOn("createDebugAppBundle")
    // Resolve to File at configuration time — doLast must not invoke Task.project at execution time.
    val appExeFile = layout.buildDirectory.file(
        "bin/macosArm64/debugExecutable/YoPt.app/Contents/MacOS/YoPt"
    ).get().asFile
    doLast {
        ProcessBuilder(appExeFile.absolutePath)
            .inheritIO()
            .start()
            .waitFor()
    }
}
